var customNavTree5 = WpNavBar.readTree({
"childArray" : [{   sTitle:'Home',
    bIsWebPath:true,
    sUrl:'index.html'},{   sDescription:'Productions',
    sTitle:'Productions',
    bIsWebPath:true,
    sUrl:'productions.html',"childArray" : [{   sDescription:'Austen\'s Women',
        sTitle:'Austen\'s Women',
        bIsWebPath:true,
        sUrl:'ausein.html'},{   sDescription:'I, Elizabeth',
        sTitle:'I, Elizabeth',
        bIsWebPath:true,
        sUrl:'elizabeth.html'}]},{   sDescription:'Tour Dates for Austin\'s Women',
    sTitle:'Tour Dates',
    bIsWebPath:true,
    sUrl:'austintourdates.html'},{   sDescription:'Meet The Team',
    sTitle:'Meet The Team',
    bIsWebPath:true,
    sUrl:'team.html'},{   sDescription:'News',
    sTitle:'News',
    bIsWebPath:true,
    sUrl:'news.html'},{   sDescription:'Links to other sites',
    sTitle:'Links',
    bIsWebPath:true,
    sUrl:'links.html'},{   sDescription:'Contact Us',
    sTitle:'Contact Us',
    bIsWebPath:true,
    sUrl:'contact.html'}]
});